### PR TITLE
Add include directory based on CMAKE variables to assimp

### PR DESCRIPTION
**Pull request by alicemargatroid**
Looks like someone missed the ASSIMP_INCLUDE_DIR variable :-1:

### CODE REVIEW

**Comment by Squareys** [comment]
Assimp related code is probably me! 😅

The problem is somewhere else, though:
~~~
 target_link_libraries(AssimpImporter Magnum::Magnum Assimp::Assimp)
~~~
uses an imported target `Assimp::Assimp` which is defined in `FindAssimp.cmake` and usually automatically sets the include directory! It is probably not found there.

@alicemargatroid Which system are you on? I remember this being enabled on at least one CI, so this must be a platform specific problem.

**Comment by mosra** [comment]
@alicemargatroid oh! terribly sorry about this. Thanks for the patch!

@Squareys the line you mean affects `AssimpImporter`, but not `AssimpImporterObjects` .. in our case (and also in case of the CI, unfortunately) AssImp was installed in the default locations, making the includes "just work". Putting its headers into some non-implicit location exposes this problem.

**Comment by alicemargatroid** [comment]
@mosra No problem, very easy oversight to make.

@Squareys This is not platform specific; I compile everything myself (I don't use the package manager or whatever to install my dependencies), so I need Magnum to know where I've assigned `ASSIMP_INCLUDE_DIR`, otherwise it won't pick up my includes.

Spent a day and a half scratching my head over this before just directly diff'ing the `CMakeLists.txt` of `JpegImporter` vs `AssimpImporter`, and it turned out to be this tiny innocuous line :)

Can confirm this fixes builds for me on Ubuntu, MingW, and OSX.

**Comment by mosra** [comment]
Merged as 530c75c5dd90b1d9ea0f68aeb7c462b7737af545 -- I replaced `${ASSIMP_INCLUDE_DIR}` with `$<TARGET_PROPERTY:Assimp::Assimp,INTERFACE_INCLUDE_DIRECTORIES>` to avoid using internal variables of the Find module.

Hope I didn't break it for you again with that change :D

**Comment by alicemargatroid** [comment]
@mosra Why is such a change not done here then: 
https://github.com/mosra/magnum-plugins/blob/master/src/MagnumPlugins/JpegImporter/CMakeLists.txt#L50

**Comment by mosra** [comment]
Because `FindJPEG.cmake` [doesn't have imported targets](https://cmake.org/cmake/help/v3.9/module/FindJPEG.html) yet ...

**Pull request closed without merging**
