### PR TITLE
More Platforms on AppVeyor

### PR DESCRIPTION
**Pull request by Squareys**
Hi @mosra !

I am secretly trying to get AppVeyor to build magnum-plugins with msvc amd64 (see gitter).
As a result, mingw-w64 platform has been added to get the neat structure which you established on mosra/magnum :)

If having all these platforms on magnum-plugins aswell is not desired, you may reject the PR (once I'm done testing msvc amd64, heh ;) )

Regards, Squareys.

### CODE REVIEW

**Comment by Squareys** [comment]
It seems to fail to download libjpeg turbo, but only on msvc, not on mingw. Very strange.

**Comment by Squareys** [comment]
And on MinGW it fails building libjpeg turbo, but "succeeds" the AppVeyor build.

**Comment by mosra** [comment]
I reused a bunch of things from your PR and continuing in an `appveyor-updates` branch, along with support for Windows RT. The switch to 64bit MSVC will be done later.

Will close this once that branch gets merged to master.

**Comment by Squareys** [comment]
@mosra Thanks! And sorry I kinda abruptly stopped working on this PR. After weird AppVeyor installation errors, I succeeded with 

> I am secretly trying to get AppVeyor to build magnum-plugins with msvc amd64

offline. I had accidentally loaded the release version of OpenGexImporter.dll while linking against the debug. Result was a mismatch of data structures returned by importer state.

**Comment by mosra** [comment]
Yes I remember :) The issue with LibJPEG was that it didn't work properly with MinGW until 1.5.0 (trivial error in CMake buildscripts, I guess nobody tested with MinGW and `cmd.exe` together).

Done in 73c0486f4d092e8e5d8f59059e08eb40d42442a9.

**Pull request closed without merging**
